module.exports = {
  preset: 'jest-expo',
  cacheDirectory: '<rootDir>/.jest-cache',
  setupFiles: ['<rootDir>/jest.setup.js'],
  setupFilesAfterEnv: [],
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)',
  ],
  testMatch: ['**/__tests__/**/*.test.js'],
  // Use jsdom for web component tests
  testEnvironment: process.env.TEST_ENV === 'jsdom' ? 'jsdom' : undefined,
  // Override test environment for web test files
  projects: [
    {
      displayName: 'native',
      testMatch: ['**/__tests__/**/*.test.js', '!**/__tests__/**/*.web.test.js'],
      preset: 'jest-expo',
      cacheDirectory: '<rootDir>/.jest-cache/native',
      setupFiles: ['<rootDir>/jest.setup.js'],
      transformIgnorePatterns: [
        'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)',
      ],
      moduleNameMapper: {
        '^immer$': '<rootDir>/node_modules/immer/dist/cjs/index.js',
        '^react-redux$': '<rootDir>/node_modules/react-redux/dist/cjs/react-redux.development.cjs',
        '^@/(.*)$': '<rootDir>/src/$1',
        '^@app/(.*)$': '<rootDir>/src/app/$1',
        '^@platform/(.*)$': '<rootDir>/src/platform/$1',
        '^@theme/(.*)$': '<rootDir>/src/theme/$1',
        '^@store/(.*)$': '<rootDir>/src/store/$1',
        '^@features/(.*)$': '<rootDir>/src/features/$1',
        '^@services/(.*)$': '<rootDir>/src/services/$1',
        '^@offline/(.*)$': '<rootDir>/src/offline/$1',
        '^@security/(.*)$': '<rootDir>/src/security/$1',
        '^@bootstrap/(.*)$': '<rootDir>/src/bootstrap/$1',
        '^@hooks/(.*)$': '<rootDir>/src/hooks/$1',
        '^@utils$': '<rootDir>/src/utils',
        '^@utils/(.*)$': '<rootDir>/src/utils/$1',
        '^@navigation/(.*)$': '<rootDir>/src/navigation/$1',
        '^@config$': '<rootDir>/src/config',
        '^@config/(.*)$': '<rootDir>/src/config/$1',
        '^@i18n$': '<rootDir>/src/i18n',
        '^@i18n/(.*)$': '<rootDir>/src/i18n/$1',
        '^@errors$': '<rootDir>/src/errors',
        '^@errors/fallback\\.ui$': '<rootDir>/src/errors/fallback.ui.native.jsx',
        '^@errors/(.*)$': '<rootDir>/src/errors/$1',
        '^@logging$': '<rootDir>/src/logging',
        '^@logging/(.*)$': '<rootDir>/src/logging/$1',
        '^@debug$': '<rootDir>/src/debug',
        '^@debug/(.*)$': '<rootDir>/src/debug/$1',
        '^react-native/Libraries/BatchedBridge/NativeModules$': '<rootDir>/test/mocks/NativeModules.js',
        '^expo/src/async-require/messageSocket$': '<rootDir>/test/mocks/expoMessageSocket.js',
        '^expo-modules-core/src/polyfill/dangerous-internal$': '<rootDir>/test/mocks/expoDangerousInternal.js',
      },
    },
    {
      displayName: 'web',
      testMatch: ['**/__tests__/**/*.web.test.js'],
      testEnvironment: 'jsdom',
      cacheDirectory: '<rootDir>/.jest-cache/web',
      setupFiles: ['<rootDir>/jest.setup.web.js'],
      transformIgnorePatterns: [
        'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)',
      ],
      moduleNameMapper: {
        '^immer$': '<rootDir>/node_modules/immer/dist/cjs/index.js',
        '^react-redux$': '<rootDir>/node_modules/react-redux/dist/cjs/react-redux.development.cjs',
        '^@/(.*)$': '<rootDir>/src/$1',
        '^@app/(.*)$': '<rootDir>/src/app/$1',
        '^@platform/(.*)$': '<rootDir>/src/platform/$1',
        '^@theme/(.*)$': '<rootDir>/src/theme/$1',
        '^@store/(.*)$': '<rootDir>/src/store/$1',
        '^@features/(.*)$': '<rootDir>/src/features/$1',
        '^@services/(.*)$': '<rootDir>/src/services/$1',
        '^@offline/(.*)$': '<rootDir>/src/offline/$1',
        '^@security/(.*)$': '<rootDir>/src/security/$1',
        '^@bootstrap/(.*)$': '<rootDir>/src/bootstrap/$1',
        '^@hooks/(.*)$': '<rootDir>/src/hooks/$1',
        '^@utils$': '<rootDir>/src/utils',
        '^@utils/(.*)$': '<rootDir>/src/utils/$1',
        '^@navigation/(.*)$': '<rootDir>/src/navigation/$1',
        '^@config$': '<rootDir>/src/config',
        '^@config/(.*)$': '<rootDir>/src/config/$1',
        '^@i18n$': '<rootDir>/src/i18n',
        '^@i18n/(.*)$': '<rootDir>/src/i18n/$1',
        '^@errors$': '<rootDir>/src/errors',
        '^@errors/fallback\\.ui$': '<rootDir>/src/errors/fallback.ui.web.jsx',
        '^@errors/(.*)$': '<rootDir>/src/errors/$1',
        '^@logging$': '<rootDir>/src/logging',
        '^@logging/(.*)$': '<rootDir>/src/logging/$1',
        '^@debug$': '<rootDir>/src/debug',
        '^@debug/(.*)$': '<rootDir>/src/debug/$1',
        '^react-native/Libraries/BatchedBridge/NativeModules$': '<rootDir>/test/mocks/NativeModules.js',
        '^expo/src/async-require/messageSocket$': '<rootDir>/test/mocks/expoMessageSocket.js',
        '^expo-modules-core/src/polyfill/dangerous-internal$': '<rootDir>/test/mocks/expoDangerousInternal.js',
      },
    },
  ],
  collectCoverageFrom: [
    'src/**/*.{js,jsx}',
    '!src/**/*.test.{js,jsx}',
    '!src/**/index.{js,jsx}',
    '!src/**/*.styles.{js,jsx}',
    // Exclude Platform.select files (platform selector files, similar to index files)
    // These files only contain Platform.select() calls which are tested via platform-specific implementations
    '!src/**/MainLayout.jsx',
    '!src/**/AuthLayout.jsx',
    '!src/**/ModalLayout.jsx',
  ],
  coverageThreshold: {
    global: {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
  passWithNoTests: true,
};

