/**
 * API Endpoints Registry
 * File: endpoints.js
 */

import { API_BASE_URL, API_VERSION } from '@config/env';

const normalizeBaseUrl = (value) => String(value || '').replace(/\/+$/, '');
const baseUrl = `${normalizeBaseUrl(API_BASE_URL)}/api/${API_VERSION}`;

export const endpoints = {
  HEALTH: `${normalizeBaseUrl(API_BASE_URL)}/health`,
  AUTH: {
    CSRF_TOKEN: `${baseUrl}/auth/csrf-token`,
    IDENTIFY: `${baseUrl}/auth/identify`,
    LOGIN: `${baseUrl}/auth/login`,
    REGISTER: `${baseUrl}/auth/register`,
    REFRESH: `${baseUrl}/auth/refresh`,
    LOGOUT: `${baseUrl}/auth/logout`,
    ME: `${baseUrl}/auth/me`,
    FORGOT_PASSWORD: `${baseUrl}/auth/forgot-password`,
    RESET_PASSWORD: `${baseUrl}/auth/reset-password`,
    CHANGE_PASSWORD: `${baseUrl}/auth/change-password`,
    VERIFY_EMAIL: `${baseUrl}/auth/verify-email`,
    VERIFY_PHONE: `${baseUrl}/auth/verify-phone`,
    RESEND_VERIFICATION: `${baseUrl}/auth/resend-verification`,
  },
  USER_SESSIONS: {
    LIST: `${baseUrl}/user-sessions`,
    GET: (id) => `${baseUrl}/user-sessions/${id}`,
    DELETE: (id) => `${baseUrl}/user-sessions/${id}`,
  },
  TENANTS: {
    LIST: `${baseUrl}/tenants`,
    CREATE: `${baseUrl}/tenants`,
    GET: (id) => `${baseUrl}/tenants/${id}`,
    UPDATE: (id) => `${baseUrl}/tenants/${id}`,
    DELETE: (id) => `${baseUrl}/tenants/${id}`,
  },
  FACILITIES: {
    LIST: `${baseUrl}/facilities`,
    CREATE: `${baseUrl}/facilities`,
    GET: (id) => `${baseUrl}/facilities/${id}`,
    UPDATE: (id) => `${baseUrl}/facilities/${id}`,
    DELETE: (id) => `${baseUrl}/facilities/${id}`,
    GET_BRANCHES: (id) => `${baseUrl}/facilities/${id}/branches`,
  },
  BRANCHES: {
    LIST: `${baseUrl}/branches`,
    CREATE: `${baseUrl}/branches`,
    GET: (id) => `${baseUrl}/branches/${id}`,
    UPDATE: (id) => `${baseUrl}/branches/${id}`,
    DELETE: (id) => `${baseUrl}/branches/${id}`,
  },
  DEPARTMENTS: {
    LIST: `${baseUrl}/departments`,
    CREATE: `${baseUrl}/departments`,
    GET: (id) => `${baseUrl}/departments/${id}`,
    UPDATE: (id) => `${baseUrl}/departments/${id}`,
    DELETE: (id) => `${baseUrl}/departments/${id}`,
    GET_UNITS: (id) => `${baseUrl}/departments/${id}/units`,
  },
  UNITS: {
    LIST: `${baseUrl}/units`,
    CREATE: `${baseUrl}/units`,
    GET: (id) => `${baseUrl}/units/${id}`,
    UPDATE: (id) => `${baseUrl}/units/${id}`,
    DELETE: (id) => `${baseUrl}/units/${id}`,
  },
  ROOMS: {
    LIST: `${baseUrl}/rooms`,
    CREATE: `${baseUrl}/rooms`,
    GET: (id) => `${baseUrl}/rooms/${id}`,
    UPDATE: (id) => `${baseUrl}/rooms/${id}`,
    DELETE: (id) => `${baseUrl}/rooms/${id}`,
  },
  WARDS: {
    LIST: `${baseUrl}/wards`,
    CREATE: `${baseUrl}/wards`,
    GET: (id) => `${baseUrl}/wards/${id}`,
    UPDATE: (id) => `${baseUrl}/wards/${id}`,
    DELETE: (id) => `${baseUrl}/wards/${id}`,
    GET_BEDS: (id) => `${baseUrl}/wards/${id}/beds`,
  },
  BEDS: {
    LIST: `${baseUrl}/beds`,
    CREATE: `${baseUrl}/beds`,
    GET: (id) => `${baseUrl}/beds/${id}`,
    UPDATE: (id) => `${baseUrl}/beds/${id}`,
    DELETE: (id) => `${baseUrl}/beds/${id}`,
  },
  CONTACTS: {
    LIST: `${baseUrl}/contacts`,
    CREATE: `${baseUrl}/contacts`,
    GET: (id) => `${baseUrl}/contacts/${id}`,
    UPDATE: (id) => `${baseUrl}/contacts/${id}`,
    DELETE: (id) => `${baseUrl}/contacts/${id}`,
  },
  USER_PROFILES: {
    LIST: `${baseUrl}/user-profiles`,
    CREATE: `${baseUrl}/user-profiles`,
    GET: (id) => `${baseUrl}/user-profiles/${id}`,
    UPDATE: (id) => `${baseUrl}/user-profiles/${id}`,
    DELETE: (id) => `${baseUrl}/user-profiles/${id}`,
  },
  ROLES: {
    LIST: `${baseUrl}/roles`,
    CREATE: `${baseUrl}/roles`,
    GET: (id) => `${baseUrl}/roles/${id}`,
    UPDATE: (id) => `${baseUrl}/roles/${id}`,
    DELETE: (id) => `${baseUrl}/roles/${id}`,
  },
  PERMISSIONS: {
    LIST: `${baseUrl}/permissions`,
    CREATE: `${baseUrl}/permissions`,
    GET: (id) => `${baseUrl}/permissions/${id}`,
    UPDATE: (id) => `${baseUrl}/permissions/${id}`,
    DELETE: (id) => `${baseUrl}/permissions/${id}`,
  },
  ROLE_PERMISSIONS: {
    LIST: `${baseUrl}/role-permissions`,
    CREATE: `${baseUrl}/role-permissions`,
    GET: (id) => `${baseUrl}/role-permissions/${id}`,
    UPDATE: (id) => `${baseUrl}/role-permissions/${id}`,
    DELETE: (id) => `${baseUrl}/role-permissions/${id}`,
  },
  USER_ROLES: {
    LIST: `${baseUrl}/user-roles`,
    CREATE: `${baseUrl}/user-roles`,
    GET: (id) => `${baseUrl}/user-roles/${id}`,
    UPDATE: (id) => `${baseUrl}/user-roles/${id}`,
    DELETE: (id) => `${baseUrl}/user-roles/${id}`,
  },
  API_KEYS: {
    LIST: `${baseUrl}/api-keys`,
    CREATE: `${baseUrl}/api-keys`,
    GET: (id) => `${baseUrl}/api-keys/${id}`,
    UPDATE: (id) => `${baseUrl}/api-keys/${id}`,
    DELETE: (id) => `${baseUrl}/api-keys/${id}`,
  },
  API_KEY_PERMISSIONS: {
    LIST: `${baseUrl}/api-key-permissions`,
    CREATE: `${baseUrl}/api-key-permissions`,
    GET: (id) => `${baseUrl}/api-key-permissions/${id}`,
    UPDATE: (id) => `${baseUrl}/api-key-permissions/${id}`,
    DELETE: (id) => `${baseUrl}/api-key-permissions/${id}`,
  },
  USER_MFAS: {
    LIST: `${baseUrl}/user-mfas`,
    CREATE: `${baseUrl}/user-mfas`,
    GET: (id) => `${baseUrl}/user-mfas/${id}`,
    UPDATE: (id) => `${baseUrl}/user-mfas/${id}`,
    DELETE: (id) => `${baseUrl}/user-mfas/${id}`,
    VERIFY: (id) => `${baseUrl}/user-mfas/${id}/verify`,
    ENABLE: (id) => `${baseUrl}/user-mfas/${id}/enable`,
    DISABLE: (id) => `${baseUrl}/user-mfas/${id}/disable`,
  },
  OAUTH_ACCOUNTS: {
    LIST: `${baseUrl}/oauth-accounts`,
    CREATE: `${baseUrl}/oauth-accounts`,
    GET: (id) => `${baseUrl}/oauth-accounts/${id}`,
    UPDATE: (id) => `${baseUrl}/oauth-accounts/${id}`,
    DELETE: (id) => `${baseUrl}/oauth-accounts/${id}`,
  },
  PATIENTS: {
    LIST: `${baseUrl}/patients`,
    CREATE: `${baseUrl}/patients`,
    GET: (id) => `${baseUrl}/patients/${id}`,
    UPDATE: (id) => `${baseUrl}/patients/${id}`,
    DELETE: (id) => `${baseUrl}/patients/${id}`,
    GET_IDENTIFIERS: (id) => `${baseUrl}/patients/${id}/identifiers`,
    GET_CONTACTS: (id) => `${baseUrl}/patients/${id}/contacts`,
    GET_GUARDIANS: (id) => `${baseUrl}/patients/${id}/guardians`,
    GET_ALLERGIES: (id) => `${baseUrl}/patients/${id}/allergies`,
    GET_MEDICAL_HISTORIES: (id) => `${baseUrl}/patients/${id}/medical-histories`,
    GET_DOCUMENTS: (id) => `${baseUrl}/patients/${id}/documents`,
  },
  PATIENT_IDENTIFIERS: {
    LIST: `${baseUrl}/patient-identifiers`,
    CREATE: `${baseUrl}/patient-identifiers`,
    GET: (id) => `${baseUrl}/patient-identifiers/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-identifiers/${id}`,
    DELETE: (id) => `${baseUrl}/patient-identifiers/${id}`,
  },
  PATIENT_CONTACTS: {
    LIST: `${baseUrl}/patient-contacts`,
    CREATE: `${baseUrl}/patient-contacts`,
    GET: (id) => `${baseUrl}/patient-contacts/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-contacts/${id}`,
    DELETE: (id) => `${baseUrl}/patient-contacts/${id}`,
  },
  PATIENT_GUARDIANS: {
    LIST: `${baseUrl}/patient-guardians`,
    CREATE: `${baseUrl}/patient-guardians`,
    GET: (id) => `${baseUrl}/patient-guardians/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-guardians/${id}`,
    DELETE: (id) => `${baseUrl}/patient-guardians/${id}`,
  },
  PATIENT_ALLERGIES: {
    LIST: `${baseUrl}/patient-allergies`,
    CREATE: `${baseUrl}/patient-allergies`,
    GET: (id) => `${baseUrl}/patient-allergies/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-allergies/${id}`,
    DELETE: (id) => `${baseUrl}/patient-allergies/${id}`,
  },
  PATIENT_MEDICAL_HISTORIES: {
    LIST: `${baseUrl}/patient-medical-histories`,
    CREATE: `${baseUrl}/patient-medical-histories`,
    GET: (id) => `${baseUrl}/patient-medical-histories/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-medical-histories/${id}`,
    DELETE: (id) => `${baseUrl}/patient-medical-histories/${id}`,
  },
  PATIENT_DOCUMENTS: {
    LIST: `${baseUrl}/patient-documents`,
    CREATE: `${baseUrl}/patient-documents`,
    GET: (id) => `${baseUrl}/patient-documents/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-documents/${id}`,
    DELETE: (id) => `${baseUrl}/patient-documents/${id}`,
  },
  CONSENTS: {
    LIST: `${baseUrl}/consents`,
    CREATE: `${baseUrl}/consents`,
    GET: (id) => `${baseUrl}/consents/${id}`,
    UPDATE: (id) => `${baseUrl}/consents/${id}`,
    DELETE: (id) => `${baseUrl}/consents/${id}`,
  },
  TERMS_ACCEPTANCES: {
    LIST: `${baseUrl}/terms-acceptances`,
    CREATE: `${baseUrl}/terms-acceptances`,
    GET: (id) => `${baseUrl}/terms-acceptances/${id}`,
    DELETE: (id) => `${baseUrl}/terms-acceptances/${id}`,
  },
  APPOINTMENTS: {
    LIST: `${baseUrl}/appointments`,
    CREATE: `${baseUrl}/appointments`,
    GET: (id) => `${baseUrl}/appointments/${id}`,
    UPDATE: (id) => `${baseUrl}/appointments/${id}`,
    DELETE: (id) => `${baseUrl}/appointments/${id}`,
    CANCEL: (id) => `${baseUrl}/appointments/${id}/cancel`,
  },
  APPOINTMENT_PARTICIPANTS: {
    LIST: `${baseUrl}/appointment-participants`,
    CREATE: `${baseUrl}/appointment-participants`,
    GET: (id) => `${baseUrl}/appointment-participants/${id}`,
    UPDATE: (id) => `${baseUrl}/appointment-participants/${id}`,
    DELETE: (id) => `${baseUrl}/appointment-participants/${id}`,
  },
  APPOINTMENT_REMINDERS: {
    LIST: `${baseUrl}/appointment-reminders`,
    CREATE: `${baseUrl}/appointment-reminders`,
    GET: (id) => `${baseUrl}/appointment-reminders/${id}`,
    UPDATE: (id) => `${baseUrl}/appointment-reminders/${id}`,
    DELETE: (id) => `${baseUrl}/appointment-reminders/${id}`,
    MARK_SENT: (id) => `${baseUrl}/appointment-reminders/${id}/mark-sent`,
  },
  PROVIDER_SCHEDULES: {
    LIST: `${baseUrl}/provider-schedules`,
    CREATE: `${baseUrl}/provider-schedules`,
    GET: (id) => `${baseUrl}/provider-schedules/${id}`,
    UPDATE: (id) => `${baseUrl}/provider-schedules/${id}`,
    DELETE: (id) => `${baseUrl}/provider-schedules/${id}`,
  },
  AVAILABILITY_SLOTS: {
    LIST: `${baseUrl}/availability-slots`,
    CREATE: `${baseUrl}/availability-slots`,
    GET: (id) => `${baseUrl}/availability-slots/${id}`,
    UPDATE: (id) => `${baseUrl}/availability-slots/${id}`,
    DELETE: (id) => `${baseUrl}/availability-slots/${id}`,
  },
  VISIT_QUEUES: {
    LIST: `${baseUrl}/visit-queues`,
    CREATE: `${baseUrl}/visit-queues`,
    GET: (id) => `${baseUrl}/visit-queues/${id}`,
    UPDATE: (id) => `${baseUrl}/visit-queues/${id}`,
    DELETE: (id) => `${baseUrl}/visit-queues/${id}`,
    PRIORITIZE: (id) => `${baseUrl}/visit-queues/${id}/prioritize`,
  },
  OPD_FLOWS: {
    LIST: `${baseUrl}/opd-flows`,
    GET: (id) => `${baseUrl}/opd-flows/${id}`,
    START: `${baseUrl}/opd-flows/start`,
    BOOTSTRAP: `${baseUrl}/opd-flows/bootstrap`,
    PAY_CONSULTATION: (id) => `${baseUrl}/opd-flows/${id}/pay-consultation`,
    RECORD_VITALS: (id) => `${baseUrl}/opd-flows/${id}/record-vitals`,
    ASSIGN_DOCTOR: (id) => `${baseUrl}/opd-flows/${id}/assign-doctor`,
    DOCTOR_REVIEW: (id) => `${baseUrl}/opd-flows/${id}/doctor-review`,
    DISPOSITION: (id) => `${baseUrl}/opd-flows/${id}/disposition`,
    CORRECT_STAGE: (id) => `${baseUrl}/opd-flows/${id}/correct-stage`,
  },
  IPD_FLOWS: {
    LIST: `${baseUrl}/ipd-flows`,
    GET: (id) => `${baseUrl}/ipd-flows/${id}`,
    RESOLVE_LEGACY: (resource, id) => `${baseUrl}/ipd-flows/resolve-legacy/${resource}/${id}`,
    START: `${baseUrl}/ipd-flows/start`,
    START_ICU_STAY: (id) => `${baseUrl}/ipd-flows/${id}/start-icu-stay`,
    END_ICU_STAY: (id) => `${baseUrl}/ipd-flows/${id}/end-icu-stay`,
    ADD_ICU_OBSERVATION: (id) => `${baseUrl}/ipd-flows/${id}/add-icu-observation`,
    ADD_CRITICAL_ALERT: (id) => `${baseUrl}/ipd-flows/${id}/add-critical-alert`,
    RESOLVE_CRITICAL_ALERT: (id) => `${baseUrl}/ipd-flows/${id}/resolve-critical-alert`,
    ASSIGN_BED: (id) => `${baseUrl}/ipd-flows/${id}/assign-bed`,
    RELEASE_BED: (id) => `${baseUrl}/ipd-flows/${id}/release-bed`,
    REQUEST_TRANSFER: (id) => `${baseUrl}/ipd-flows/${id}/request-transfer`,
    UPDATE_TRANSFER: (id) => `${baseUrl}/ipd-flows/${id}/update-transfer`,
    ADD_WARD_ROUND: (id) => `${baseUrl}/ipd-flows/${id}/add-ward-round`,
    ADD_NURSING_NOTE: (id) => `${baseUrl}/ipd-flows/${id}/add-nursing-note`,
    ADD_MEDICATION_ADMINISTRATION: (id) =>
      `${baseUrl}/ipd-flows/${id}/add-medication-administration`,
    PLAN_DISCHARGE: (id) => `${baseUrl}/ipd-flows/${id}/plan-discharge`,
    FINALIZE_DISCHARGE: (id) => `${baseUrl}/ipd-flows/${id}/finalize-discharge`,
  },
  DOCTORS: {
    LIST: `${baseUrl}/doctors`,
    CREATE: `${baseUrl}/doctors`,
    GET: (id) => `${baseUrl}/doctors/${id}`,
    UPDATE: (id) => `${baseUrl}/doctors/${id}`,
  },
  ENCOUNTERS: {
    LIST: `${baseUrl}/encounters`,
    CREATE: `${baseUrl}/encounters`,
    GET: (id) => `${baseUrl}/encounters/${id}`,
    UPDATE: (id) => `${baseUrl}/encounters/${id}`,
    DELETE: (id) => `${baseUrl}/encounters/${id}`,
  },
  CLINICAL_NOTES: {
    LIST: `${baseUrl}/clinical-notes`,
    CREATE: `${baseUrl}/clinical-notes`,
    GET: (id) => `${baseUrl}/clinical-notes/${id}`,
    UPDATE: (id) => `${baseUrl}/clinical-notes/${id}`,
    DELETE: (id) => `${baseUrl}/clinical-notes/${id}`,
  },
  DIAGNOSES: {
    LIST: `${baseUrl}/diagnoses`,
    CREATE: `${baseUrl}/diagnoses`,
    GET: (id) => `${baseUrl}/diagnoses/${id}`,
    UPDATE: (id) => `${baseUrl}/diagnoses/${id}`,
    DELETE: (id) => `${baseUrl}/diagnoses/${id}`,
  },
  PROCEDURES: {
    LIST: `${baseUrl}/procedures`,
    CREATE: `${baseUrl}/procedures`,
    GET: (id) => `${baseUrl}/procedures/${id}`,
    UPDATE: (id) => `${baseUrl}/procedures/${id}`,
    DELETE: (id) => `${baseUrl}/procedures/${id}`,
  },
  VITAL_SIGNS: {
    LIST: `${baseUrl}/vital-signs`,
    CREATE: `${baseUrl}/vital-signs`,
    GET: (id) => `${baseUrl}/vital-signs/${id}`,
    UPDATE: (id) => `${baseUrl}/vital-signs/${id}`,
    DELETE: (id) => `${baseUrl}/vital-signs/${id}`,
  },
  CARE_PLANS: {
    LIST: `${baseUrl}/care-plans`,
    CREATE: `${baseUrl}/care-plans`,
    GET: (id) => `${baseUrl}/care-plans/${id}`,
    UPDATE: (id) => `${baseUrl}/care-plans/${id}`,
    DELETE: (id) => `${baseUrl}/care-plans/${id}`,
  },
  CLINICAL_ALERTS: {
    LIST: `${baseUrl}/clinical-alerts`,
    CREATE: `${baseUrl}/clinical-alerts`,
    GET: (id) => `${baseUrl}/clinical-alerts/${id}`,
    UPDATE: (id) => `${baseUrl}/clinical-alerts/${id}`,
    DELETE: (id) => `${baseUrl}/clinical-alerts/${id}`,
    ACKNOWLEDGE: (id) => `${baseUrl}/clinical-alerts/${id}/acknowledge`,
    RESOLVE: (id) => `${baseUrl}/clinical-alerts/${id}/resolve`,
  },
  CLINICAL_ALERT_THRESHOLDS: {
    GET: `${baseUrl}/clinical-alert-thresholds`,
    UPDATE: `${baseUrl}/clinical-alert-thresholds`,
  },
  REFERRALS: {
    LIST: `${baseUrl}/referrals`,
    CREATE: `${baseUrl}/referrals`,
    GET: (id) => `${baseUrl}/referrals/${id}`,
    UPDATE: (id) => `${baseUrl}/referrals/${id}`,
    DELETE: (id) => `${baseUrl}/referrals/${id}`,
    APPROVE: (id) => `${baseUrl}/referrals/${id}/approve`,
    START: (id) => `${baseUrl}/referrals/${id}/start`,
    CANCEL: (id) => `${baseUrl}/referrals/${id}/cancel`,
    REDEEM: (id) => `${baseUrl}/referrals/${id}/redeem`,
  },
  FOLLOW_UPS: {
    LIST: `${baseUrl}/follow-ups`,
    CREATE: `${baseUrl}/follow-ups`,
    GET: (id) => `${baseUrl}/follow-ups/${id}`,
    UPDATE: (id) => `${baseUrl}/follow-ups/${id}`,
    DELETE: (id) => `${baseUrl}/follow-ups/${id}`,
    COMPLETE: (id) => `${baseUrl}/follow-ups/${id}/complete`,
    CANCEL: (id) => `${baseUrl}/follow-ups/${id}/cancel`,
    REMINDER_DISPATCH: `${baseUrl}/follow-ups/reminders/dispatch`,
    REMINDER_DUE_SUMMARY: `${baseUrl}/follow-ups/reminders/due-summary`,
  },
  CLINICAL_TERMS: {
    SUGGESTIONS: `${baseUrl}/clinical-terms/suggestions`,
  },
  CLINICAL_TERM_FAVORITES: {
    LIST: `${baseUrl}/clinical-term-favorites`,
    CREATE: `${baseUrl}/clinical-term-favorites`,
    DELETE: (id) => `${baseUrl}/clinical-term-favorites/${id}`,
  },
  ADMISSIONS: {
    LIST: `${baseUrl}/admissions`,
    CREATE: `${baseUrl}/admissions`,
    GET: (id) => `${baseUrl}/admissions/${id}`,
    UPDATE: (id) => `${baseUrl}/admissions/${id}`,
    DELETE: (id) => `${baseUrl}/admissions/${id}`,
    DISCHARGE: (id) => `${baseUrl}/admissions/${id}/discharge`,
    TRANSFER: (id) => `${baseUrl}/admissions/${id}/transfer`,
  },
  BED_ASSIGNMENTS: {
    LIST: `${baseUrl}/bed-assignments`,
    CREATE: `${baseUrl}/bed-assignments`,
    GET: (id) => `${baseUrl}/bed-assignments/${id}`,
    UPDATE: (id) => `${baseUrl}/bed-assignments/${id}`,
    DELETE: (id) => `${baseUrl}/bed-assignments/${id}`,
  },
  WARD_ROUNDS: {
    LIST: `${baseUrl}/ward-rounds`,
    CREATE: `${baseUrl}/ward-rounds`,
    GET: (id) => `${baseUrl}/ward-rounds/${id}`,
    UPDATE: (id) => `${baseUrl}/ward-rounds/${id}`,
    DELETE: (id) => `${baseUrl}/ward-rounds/${id}`,
  },
  NURSING_NOTES: {
    LIST: `${baseUrl}/nursing-notes`,
    CREATE: `${baseUrl}/nursing-notes`,
    GET: (id) => `${baseUrl}/nursing-notes/${id}`,
    UPDATE: (id) => `${baseUrl}/nursing-notes/${id}`,
    DELETE: (id) => `${baseUrl}/nursing-notes/${id}`,
  },
  MEDICATION_ADMINISTRATIONS: {
    LIST: `${baseUrl}/medication-administrations`,
    CREATE: `${baseUrl}/medication-administrations`,
    GET: (id) => `${baseUrl}/medication-administrations/${id}`,
    UPDATE: (id) => `${baseUrl}/medication-administrations/${id}`,
    DELETE: (id) => `${baseUrl}/medication-administrations/${id}`,
  },
  DISCHARGE_SUMMARIES: {
    LIST: `${baseUrl}/discharge-summaries`,
    CREATE: `${baseUrl}/discharge-summaries`,
    GET: (id) => `${baseUrl}/discharge-summaries/${id}`,
    UPDATE: (id) => `${baseUrl}/discharge-summaries/${id}`,
    DELETE: (id) => `${baseUrl}/discharge-summaries/${id}`,
    FINALIZE: (id) => `${baseUrl}/discharge-summaries/${id}/finalize`,
  },
  TRANSFER_REQUESTS: {
    LIST: `${baseUrl}/transfer-requests`,
    CREATE: `${baseUrl}/transfer-requests`,
    GET: (id) => `${baseUrl}/transfer-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/transfer-requests/${id}`,
    DELETE: (id) => `${baseUrl}/transfer-requests/${id}`,
  },
  ICU_STAYS: {
    LIST: `${baseUrl}/icu-stays`,
    CREATE: `${baseUrl}/icu-stays`,
    GET: (id) => `${baseUrl}/icu-stays/${id}`,
    UPDATE: (id) => `${baseUrl}/icu-stays/${id}`,
    DELETE: (id) => `${baseUrl}/icu-stays/${id}`,
  },
  ICU_OBSERVATIONS: {
    LIST: `${baseUrl}/icu-observations`,
    CREATE: `${baseUrl}/icu-observations`,
    GET: (id) => `${baseUrl}/icu-observations/${id}`,
    UPDATE: (id) => `${baseUrl}/icu-observations/${id}`,
    DELETE: (id) => `${baseUrl}/icu-observations/${id}`,
  },
  CRITICAL_ALERTS: {
    LIST: `${baseUrl}/critical-alerts`,
    CREATE: `${baseUrl}/critical-alerts`,
    GET: (id) => `${baseUrl}/critical-alerts/${id}`,
    UPDATE: (id) => `${baseUrl}/critical-alerts/${id}`,
    DELETE: (id) => `${baseUrl}/critical-alerts/${id}`,
  },
  THEATRE_CASES: {
    LIST: `${baseUrl}/theatre-cases`,
    CREATE: `${baseUrl}/theatre-cases`,
    GET: (id) => `${baseUrl}/theatre-cases/${id}`,
    UPDATE: (id) => `${baseUrl}/theatre-cases/${id}`,
    DELETE: (id) => `${baseUrl}/theatre-cases/${id}`,
  },
  ANESTHESIA_RECORDS: {
    LIST: `${baseUrl}/anesthesia-records`,
    CREATE: `${baseUrl}/anesthesia-records`,
    GET: (id) => `${baseUrl}/anesthesia-records/${id}`,
    UPDATE: (id) => `${baseUrl}/anesthesia-records/${id}`,
    DELETE: (id) => `${baseUrl}/anesthesia-records/${id}`,
  },
  POST_OP_NOTES: {
    LIST: `${baseUrl}/post-op-notes`,
    CREATE: `${baseUrl}/post-op-notes`,
    GET: (id) => `${baseUrl}/post-op-notes/${id}`,
    UPDATE: (id) => `${baseUrl}/post-op-notes/${id}`,
    DELETE: (id) => `${baseUrl}/post-op-notes/${id}`,
  },
  LAB_TESTS: {
    LIST: `${baseUrl}/lab-tests`,
    CREATE: `${baseUrl}/lab-tests`,
    GET: (id) => `${baseUrl}/lab-tests/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-tests/${id}`,
    DELETE: (id) => `${baseUrl}/lab-tests/${id}`,
  },
  LAB_PANELS: {
    LIST: `${baseUrl}/lab-panels`,
    CREATE: `${baseUrl}/lab-panels`,
    GET: (id) => `${baseUrl}/lab-panels/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-panels/${id}`,
    DELETE: (id) => `${baseUrl}/lab-panels/${id}`,
  },
  LAB_ORDERS: {
    LIST: `${baseUrl}/lab-orders`,
    CREATE: `${baseUrl}/lab-orders`,
    GET: (id) => `${baseUrl}/lab-orders/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-orders/${id}`,
    DELETE: (id) => `${baseUrl}/lab-orders/${id}`,
  },
  LAB_ORDER_ITEMS: {
    LIST: `${baseUrl}/lab-order-items`,
    CREATE: `${baseUrl}/lab-order-items`,
    GET: (id) => `${baseUrl}/lab-order-items/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-order-items/${id}`,
    DELETE: (id) => `${baseUrl}/lab-order-items/${id}`,
  },
  LAB_SAMPLES: {
    LIST: `${baseUrl}/lab-samples`,
    CREATE: `${baseUrl}/lab-samples`,
    GET: (id) => `${baseUrl}/lab-samples/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-samples/${id}`,
    DELETE: (id) => `${baseUrl}/lab-samples/${id}`,
  },
  LAB_RESULTS: {
    LIST: `${baseUrl}/lab-results`,
    CREATE: `${baseUrl}/lab-results`,
    GET: (id) => `${baseUrl}/lab-results/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-results/${id}`,
    DELETE: (id) => `${baseUrl}/lab-results/${id}`,
    RELEASE: (id) => `${baseUrl}/lab-results/${id}/release`,
  },
  LAB_QC_LOGS: {
    LIST: `${baseUrl}/lab-qc-logs`,
    CREATE: `${baseUrl}/lab-qc-logs`,
    GET: (id) => `${baseUrl}/lab-qc-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-qc-logs/${id}`,
    DELETE: (id) => `${baseUrl}/lab-qc-logs/${id}`,
  },
  RADIOLOGY_TESTS: {
    LIST: `${baseUrl}/radiology-tests`,
    CREATE: `${baseUrl}/radiology-tests`,
    GET: (id) => `${baseUrl}/radiology-tests/${id}`,
    UPDATE: (id) => `${baseUrl}/radiology-tests/${id}`,
    DELETE: (id) => `${baseUrl}/radiology-tests/${id}`,
  },
  RADIOLOGY_ORDERS: {
    LIST: `${baseUrl}/radiology-orders`,
    CREATE: `${baseUrl}/radiology-orders`,
    GET: (id) => `${baseUrl}/radiology-orders/${id}`,
    UPDATE: (id) => `${baseUrl}/radiology-orders/${id}`,
    DELETE: (id) => `${baseUrl}/radiology-orders/${id}`,
  },
  RADIOLOGY_RESULTS: {
    LIST: `${baseUrl}/radiology-results`,
    CREATE: `${baseUrl}/radiology-results`,
    GET: (id) => `${baseUrl}/radiology-results/${id}`,
    UPDATE: (id) => `${baseUrl}/radiology-results/${id}`,
    DELETE: (id) => `${baseUrl}/radiology-results/${id}`,
    SIGN_OFF: (id) => `${baseUrl}/radiology-results/${id}/sign-off`,
  },
  IMAGING_STUDIES: {
    LIST: `${baseUrl}/imaging-studies`,
    CREATE: `${baseUrl}/imaging-studies`,
    GET: (id) => `${baseUrl}/imaging-studies/${id}`,
    UPDATE: (id) => `${baseUrl}/imaging-studies/${id}`,
    DELETE: (id) => `${baseUrl}/imaging-studies/${id}`,
  },
  IMAGING_ASSETS: {
    LIST: `${baseUrl}/imaging-assets`,
    CREATE: `${baseUrl}/imaging-assets`,
    GET: (id) => `${baseUrl}/imaging-assets/${id}`,
    UPDATE: (id) => `${baseUrl}/imaging-assets/${id}`,
    DELETE: (id) => `${baseUrl}/imaging-assets/${id}`,
  },
  PACS_LINKS: {
    LIST: `${baseUrl}/pacs-links`,
    CREATE: `${baseUrl}/pacs-links`,
    GET: (id) => `${baseUrl}/pacs-links/${id}`,
    UPDATE: (id) => `${baseUrl}/pacs-links/${id}`,
    DELETE: (id) => `${baseUrl}/pacs-links/${id}`,
  },
  DRUGS: {
    LIST: `${baseUrl}/drugs`,
    CREATE: `${baseUrl}/drugs`,
    GET: (id) => `${baseUrl}/drugs/${id}`,
    UPDATE: (id) => `${baseUrl}/drugs/${id}`,
    DELETE: (id) => `${baseUrl}/drugs/${id}`,
  },
  DRUG_BATCHES: {
    LIST: `${baseUrl}/drug-batches`,
    CREATE: `${baseUrl}/drug-batches`,
    GET: (id) => `${baseUrl}/drug-batches/${id}`,
    UPDATE: (id) => `${baseUrl}/drug-batches/${id}`,
    DELETE: (id) => `${baseUrl}/drug-batches/${id}`,
  },
  FORMULARY_ITEMS: {
    LIST: `${baseUrl}/formulary-items`,
    CREATE: `${baseUrl}/formulary-items`,
    GET: (id) => `${baseUrl}/formulary-items/${id}`,
    UPDATE: (id) => `${baseUrl}/formulary-items/${id}`,
    DELETE: (id) => `${baseUrl}/formulary-items/${id}`,
  },
  PHARMACY_ORDERS: {
    LIST: `${baseUrl}/pharmacy-orders`,
    CREATE: `${baseUrl}/pharmacy-orders`,
    GET: (id) => `${baseUrl}/pharmacy-orders/${id}`,
    UPDATE: (id) => `${baseUrl}/pharmacy-orders/${id}`,
    DELETE: (id) => `${baseUrl}/pharmacy-orders/${id}`,
    DISPENSE: (id) => `${baseUrl}/pharmacy-orders/${id}/dispense`,
  },
  PHARMACY_ORDER_ITEMS: {
    LIST: `${baseUrl}/pharmacy-order-items`,
    CREATE: `${baseUrl}/pharmacy-order-items`,
    GET: (id) => `${baseUrl}/pharmacy-order-items/${id}`,
    UPDATE: (id) => `${baseUrl}/pharmacy-order-items/${id}`,
    DELETE: (id) => `${baseUrl}/pharmacy-order-items/${id}`,
  },
  DISPENSE_LOGS: {
    LIST: `${baseUrl}/dispense-logs`,
    CREATE: `${baseUrl}/dispense-logs`,
    GET: (id) => `${baseUrl}/dispense-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/dispense-logs/${id}`,
    DELETE: (id) => `${baseUrl}/dispense-logs/${id}`,
  },
  ADVERSE_EVENTS: {
    LIST: `${baseUrl}/adverse-events`,
    CREATE: `${baseUrl}/adverse-events`,
    GET: (id) => `${baseUrl}/adverse-events/${id}`,
    UPDATE: (id) => `${baseUrl}/adverse-events/${id}`,
    DELETE: (id) => `${baseUrl}/adverse-events/${id}`,
  },
  INVENTORY_ITEMS: {
    LIST: `${baseUrl}/inventory-items`,
    CREATE: `${baseUrl}/inventory-items`,
    GET: (id) => `${baseUrl}/inventory-items/${id}`,
    UPDATE: (id) => `${baseUrl}/inventory-items/${id}`,
    DELETE: (id) => `${baseUrl}/inventory-items/${id}`,
  },
  INVENTORY_STOCKS: {
    LIST: `${baseUrl}/inventory-stocks`,
    CREATE: `${baseUrl}/inventory-stocks`,
    GET: (id) => `${baseUrl}/inventory-stocks/${id}`,
    UPDATE: (id) => `${baseUrl}/inventory-stocks/${id}`,
    DELETE: (id) => `${baseUrl}/inventory-stocks/${id}`,
  },
  STOCK_MOVEMENTS: {
    LIST: `${baseUrl}/stock-movements`,
    CREATE: `${baseUrl}/stock-movements`,
    GET: (id) => `${baseUrl}/stock-movements/${id}`,
    UPDATE: (id) => `${baseUrl}/stock-movements/${id}`,
    DELETE: (id) => `${baseUrl}/stock-movements/${id}`,
  },
  SUPPLIERS: {
    LIST: `${baseUrl}/suppliers`,
    CREATE: `${baseUrl}/suppliers`,
    GET: (id) => `${baseUrl}/suppliers/${id}`,
    UPDATE: (id) => `${baseUrl}/suppliers/${id}`,
    DELETE: (id) => `${baseUrl}/suppliers/${id}`,
  },
  PURCHASE_REQUESTS: {
    LIST: `${baseUrl}/purchase-requests`,
    CREATE: `${baseUrl}/purchase-requests`,
    GET: (id) => `${baseUrl}/purchase-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/purchase-requests/${id}`,
    DELETE: (id) => `${baseUrl}/purchase-requests/${id}`,
  },
  PURCHASE_ORDERS: {
    LIST: `${baseUrl}/purchase-orders`,
    CREATE: `${baseUrl}/purchase-orders`,
    GET: (id) => `${baseUrl}/purchase-orders/${id}`,
    UPDATE: (id) => `${baseUrl}/purchase-orders/${id}`,
    DELETE: (id) => `${baseUrl}/purchase-orders/${id}`,
  },
  GOODS_RECEIPTS: {
    LIST: `${baseUrl}/goods-receipts`,
    CREATE: `${baseUrl}/goods-receipts`,
    GET: (id) => `${baseUrl}/goods-receipts/${id}`,
    UPDATE: (id) => `${baseUrl}/goods-receipts/${id}`,
    DELETE: (id) => `${baseUrl}/goods-receipts/${id}`,
  },
  STOCK_ADJUSTMENTS: {
    LIST: `${baseUrl}/stock-adjustments`,
    CREATE: `${baseUrl}/stock-adjustments`,
    GET: (id) => `${baseUrl}/stock-adjustments/${id}`,
    UPDATE: (id) => `${baseUrl}/stock-adjustments/${id}`,
    DELETE: (id) => `${baseUrl}/stock-adjustments/${id}`,
  },
  EMERGENCY_CASES: {
    LIST: `${baseUrl}/emergency-cases`,
    CREATE: `${baseUrl}/emergency-cases`,
    GET: (id) => `${baseUrl}/emergency-cases/${id}`,
    UPDATE: (id) => `${baseUrl}/emergency-cases/${id}`,
    DELETE: (id) => `${baseUrl}/emergency-cases/${id}`,
  },
  TRIAGE_ASSESSMENTS: {
    LIST: `${baseUrl}/triage-assessments`,
    CREATE: `${baseUrl}/triage-assessments`,
    GET: (id) => `${baseUrl}/triage-assessments/${id}`,
    UPDATE: (id) => `${baseUrl}/triage-assessments/${id}`,
    DELETE: (id) => `${baseUrl}/triage-assessments/${id}`,
  },
  EMERGENCY_RESPONSES: {
    LIST: `${baseUrl}/emergency-responses`,
    CREATE: `${baseUrl}/emergency-responses`,
    GET: (id) => `${baseUrl}/emergency-responses/${id}`,
    UPDATE: (id) => `${baseUrl}/emergency-responses/${id}`,
    DELETE: (id) => `${baseUrl}/emergency-responses/${id}`,
  },
  AMBULANCES: {
    LIST: `${baseUrl}/ambulances`,
    CREATE: `${baseUrl}/ambulances`,
    GET: (id) => `${baseUrl}/ambulances/${id}`,
    UPDATE: (id) => `${baseUrl}/ambulances/${id}`,
    DELETE: (id) => `${baseUrl}/ambulances/${id}`,
  },
  AMBULANCE_DISPATCHES: {
    LIST: `${baseUrl}/ambulance-dispatches`,
    CREATE: `${baseUrl}/ambulance-dispatches`,
    GET: (id) => `${baseUrl}/ambulance-dispatches/${id}`,
    UPDATE: (id) => `${baseUrl}/ambulance-dispatches/${id}`,
    DELETE: (id) => `${baseUrl}/ambulance-dispatches/${id}`,
  },
  AMBULANCE_TRIPS: {
    LIST: `${baseUrl}/ambulance-trips`,
    CREATE: `${baseUrl}/ambulance-trips`,
    GET: (id) => `${baseUrl}/ambulance-trips/${id}`,
    UPDATE: (id) => `${baseUrl}/ambulance-trips/${id}`,
    DELETE: (id) => `${baseUrl}/ambulance-trips/${id}`,
  },
  INVOICES: {
    LIST: `${baseUrl}/invoices`,
    CREATE: `${baseUrl}/invoices`,
    GET: (id) => `${baseUrl}/invoices/${id}`,
    UPDATE: (id) => `${baseUrl}/invoices/${id}`,
    DELETE: (id) => `${baseUrl}/invoices/${id}`,
  },
  INVOICE_ITEMS: {
    LIST: `${baseUrl}/invoice-items`,
    CREATE: `${baseUrl}/invoice-items`,
    GET: (id) => `${baseUrl}/invoice-items/${id}`,
    UPDATE: (id) => `${baseUrl}/invoice-items/${id}`,
    DELETE: (id) => `${baseUrl}/invoice-items/${id}`,
  },
  REFUNDS: {
    LIST: `${baseUrl}/refunds`,
    CREATE: `${baseUrl}/refunds`,
    GET: (id) => `${baseUrl}/refunds/${id}`,
    UPDATE: (id) => `${baseUrl}/refunds/${id}`,
    DELETE: (id) => `${baseUrl}/refunds/${id}`,
  },
  PRICING_RULES: {
    LIST: `${baseUrl}/pricing-rules`,
    CREATE: `${baseUrl}/pricing-rules`,
    GET: (id) => `${baseUrl}/pricing-rules/${id}`,
    UPDATE: (id) => `${baseUrl}/pricing-rules/${id}`,
    DELETE: (id) => `${baseUrl}/pricing-rules/${id}`,
  },
  COVERAGE_PLANS: {
    LIST: `${baseUrl}/coverage-plans`,
    CREATE: `${baseUrl}/coverage-plans`,
    GET: (id) => `${baseUrl}/coverage-plans/${id}`,
    UPDATE: (id) => `${baseUrl}/coverage-plans/${id}`,
    DELETE: (id) => `${baseUrl}/coverage-plans/${id}`,
  },
  INSURANCE_CLAIMS: {
    LIST: `${baseUrl}/insurance-claims`,
    CREATE: `${baseUrl}/insurance-claims`,
    GET: (id) => `${baseUrl}/insurance-claims/${id}`,
    UPDATE: (id) => `${baseUrl}/insurance-claims/${id}`,
    DELETE: (id) => `${baseUrl}/insurance-claims/${id}`,
    SUBMIT: (id) => `${baseUrl}/insurance-claims/${id}/submit`,
    RECONCILE: (id) => `${baseUrl}/insurance-claims/${id}/reconcile`,
  },
  PRE_AUTHORIZATIONS: {
    LIST: `${baseUrl}/pre-authorizations`,
    CREATE: `${baseUrl}/pre-authorizations`,
    GET: (id) => `${baseUrl}/pre-authorizations/${id}`,
    UPDATE: (id) => `${baseUrl}/pre-authorizations/${id}`,
    DELETE: (id) => `${baseUrl}/pre-authorizations/${id}`,
  },
  BILLING_ADJUSTMENTS: {
    LIST: `${baseUrl}/billing-adjustments`,
    CREATE: `${baseUrl}/billing-adjustments`,
    GET: (id) => `${baseUrl}/billing-adjustments/${id}`,
    UPDATE: (id) => `${baseUrl}/billing-adjustments/${id}`,
    DELETE: (id) => `${baseUrl}/billing-adjustments/${id}`,
  },
  STAFF_POSITIONS: {
    LIST: `${baseUrl}/staff-positions`,
    CREATE: `${baseUrl}/staff-positions`,
    GET: (id) => `${baseUrl}/staff-positions/${id}`,
    UPDATE: (id) => `${baseUrl}/staff-positions/${id}`,
    DELETE: (id) => `${baseUrl}/staff-positions/${id}`,
  },
  STAFF_PROFILES: {
    LIST: `${baseUrl}/staff-profiles`,
    CREATE: `${baseUrl}/staff-profiles`,
    GET: (id) => `${baseUrl}/staff-profiles/${id}`,
    UPDATE: (id) => `${baseUrl}/staff-profiles/${id}`,
    DELETE: (id) => `${baseUrl}/staff-profiles/${id}`,
  },
  STAFF_ASSIGNMENTS: {
    LIST: `${baseUrl}/staff-assignments`,
    CREATE: `${baseUrl}/staff-assignments`,
    GET: (id) => `${baseUrl}/staff-assignments/${id}`,
    UPDATE: (id) => `${baseUrl}/staff-assignments/${id}`,
    DELETE: (id) => `${baseUrl}/staff-assignments/${id}`,
  },
  STAFF_LEAVES: {
    LIST: `${baseUrl}/staff-leaves`,
    CREATE: `${baseUrl}/staff-leaves`,
    GET: (id) => `${baseUrl}/staff-leaves/${id}`,
    UPDATE: (id) => `${baseUrl}/staff-leaves/${id}`,
    DELETE: (id) => `${baseUrl}/staff-leaves/${id}`,
  },
  SHIFTS: {
    LIST: `${baseUrl}/shifts`,
    CREATE: `${baseUrl}/shifts`,
    GET: (id) => `${baseUrl}/shifts/${id}`,
    UPDATE: (id) => `${baseUrl}/shifts/${id}`,
    DELETE: (id) => `${baseUrl}/shifts/${id}`,
    PUBLISH: (id) => `${baseUrl}/shifts/${id}/publish`,
  },
  SHIFT_ASSIGNMENTS: {
    LIST: `${baseUrl}/shift-assignments`,
    CREATE: `${baseUrl}/shift-assignments`,
    GET: (id) => `${baseUrl}/shift-assignments/${id}`,
    UPDATE: (id) => `${baseUrl}/shift-assignments/${id}`,
    DELETE: (id) => `${baseUrl}/shift-assignments/${id}`,
  },
  SHIFT_SWAP_REQUESTS: {
    LIST: `${baseUrl}/shift-swap-requests`,
    CREATE: `${baseUrl}/shift-swap-requests`,
    GET: (id) => `${baseUrl}/shift-swap-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/shift-swap-requests/${id}`,
    DELETE: (id) => `${baseUrl}/shift-swap-requests/${id}`,
  },
  NURSE_ROSTERS: {
    LIST: `${baseUrl}/nurse-rosters`,
    CREATE: `${baseUrl}/nurse-rosters`,
    GET: (id) => `${baseUrl}/nurse-rosters/${id}`,
    UPDATE: (id) => `${baseUrl}/nurse-rosters/${id}`,
    DELETE: (id) => `${baseUrl}/nurse-rosters/${id}`,
    PUBLISH: (id) => `${baseUrl}/nurse-rosters/${id}/publish`,
    GENERATE: (id) => `${baseUrl}/nurse-rosters/${id}/generate`,
  },
  SHIFT_TEMPLATES: {
    LIST: `${baseUrl}/shift-templates`,
    CREATE: `${baseUrl}/shift-templates`,
    GET: (id) => `${baseUrl}/shift-templates/${id}`,
    UPDATE: (id) => `${baseUrl}/shift-templates/${id}`,
    DELETE: (id) => `${baseUrl}/shift-templates/${id}`,
  },
  ROSTER_DAY_OFFS: {
    LIST: `${baseUrl}/roster-day-offs`,
    CREATE: `${baseUrl}/roster-day-offs`,
    GET: (id) => `${baseUrl}/roster-day-offs/${id}`,
    UPDATE: (id) => `${baseUrl}/roster-day-offs/${id}`,
    DELETE: (id) => `${baseUrl}/roster-day-offs/${id}`,
  },
  STAFF_AVAILABILITIES: {
    LIST: `${baseUrl}/staff-availabilities`,
    CREATE: `${baseUrl}/staff-availabilities`,
    GET: (id) => `${baseUrl}/staff-availabilities/${id}`,
    UPDATE: (id) => `${baseUrl}/staff-availabilities/${id}`,
    DELETE: (id) => `${baseUrl}/staff-availabilities/${id}`,
  },
  PAYROLL_RUNS: {
    LIST: `${baseUrl}/payroll-runs`,
    CREATE: `${baseUrl}/payroll-runs`,
    GET: (id) => `${baseUrl}/payroll-runs/${id}`,
    UPDATE: (id) => `${baseUrl}/payroll-runs/${id}`,
    DELETE: (id) => `${baseUrl}/payroll-runs/${id}`,
  },
  PAYROLL_ITEMS: {
    LIST: `${baseUrl}/payroll-items`,
    CREATE: `${baseUrl}/payroll-items`,
    GET: (id) => `${baseUrl}/payroll-items/${id}`,
    UPDATE: (id) => `${baseUrl}/payroll-items/${id}`,
    DELETE: (id) => `${baseUrl}/payroll-items/${id}`,
  },
  HOUSEKEEPING_TASKS: {
    LIST: `${baseUrl}/housekeeping-tasks`,
    CREATE: `${baseUrl}/housekeeping-tasks`,
    GET: (id) => `${baseUrl}/housekeeping-tasks/${id}`,
    UPDATE: (id) => `${baseUrl}/housekeeping-tasks/${id}`,
    DELETE: (id) => `${baseUrl}/housekeeping-tasks/${id}`,
  },
  HOUSEKEEPING_SCHEDULES: {
    LIST: `${baseUrl}/housekeeping-schedules`,
    CREATE: `${baseUrl}/housekeeping-schedules`,
    GET: (id) => `${baseUrl}/housekeeping-schedules/${id}`,
    UPDATE: (id) => `${baseUrl}/housekeeping-schedules/${id}`,
    DELETE: (id) => `${baseUrl}/housekeeping-schedules/${id}`,
  },
  MAINTENANCE_REQUESTS: {
    LIST: `${baseUrl}/maintenance-requests`,
    CREATE: `${baseUrl}/maintenance-requests`,
    GET: (id) => `${baseUrl}/maintenance-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/maintenance-requests/${id}`,
    DELETE: (id) => `${baseUrl}/maintenance-requests/${id}`,
    TRIAGE: (id) => `${baseUrl}/maintenance-requests/${id}/triage`,
  },
  ASSETS: {
    LIST: `${baseUrl}/assets`,
    CREATE: `${baseUrl}/assets`,
    GET: (id) => `${baseUrl}/assets/${id}`,
    UPDATE: (id) => `${baseUrl}/assets/${id}`,
    DELETE: (id) => `${baseUrl}/assets/${id}`,
  },
  ASSET_SERVICE_LOGS: {
    LIST: `${baseUrl}/asset-service-logs`,
    CREATE: `${baseUrl}/asset-service-logs`,
    GET: (id) => `${baseUrl}/asset-service-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/asset-service-logs/${id}`,
    DELETE: (id) => `${baseUrl}/asset-service-logs/${id}`,
  },
  EQUIPMENT_CATEGORIES: {
    LIST: `${baseUrl}/equipment-categories`,
    CREATE: `${baseUrl}/equipment-categories`,
    GET: (id) => `${baseUrl}/equipment-categories/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-categories/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-categories/${id}`,
  },
  EQUIPMENT_REGISTRIES: {
    LIST: `${baseUrl}/equipment-registries`,
    CREATE: `${baseUrl}/equipment-registries`,
    GET: (id) => `${baseUrl}/equipment-registries/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-registries/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-registries/${id}`,
  },
  EQUIPMENT_LOCATION_HISTORIES: {
    LIST: `${baseUrl}/equipment-location-histories`,
    CREATE: `${baseUrl}/equipment-location-histories`,
    GET: (id) => `${baseUrl}/equipment-location-histories/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-location-histories/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-location-histories/${id}`,
  },
  EQUIPMENT_MAINTENANCE_PLANS: {
    LIST: `${baseUrl}/equipment-maintenance-plans`,
    CREATE: `${baseUrl}/equipment-maintenance-plans`,
    GET: (id) => `${baseUrl}/equipment-maintenance-plans/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-maintenance-plans/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-maintenance-plans/${id}`,
  },
  EQUIPMENT_WORK_ORDERS: {
    LIST: `${baseUrl}/equipment-work-orders`,
    CREATE: `${baseUrl}/equipment-work-orders`,
    GET: (id) => `${baseUrl}/equipment-work-orders/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-work-orders/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-work-orders/${id}`,
    START: (id) => `${baseUrl}/equipment-work-orders/${id}/start`,
    RETURN_TO_SERVICE: (id) => `${baseUrl}/equipment-work-orders/${id}/return-to-service`,
  },
  EQUIPMENT_CALIBRATION_LOGS: {
    LIST: `${baseUrl}/equipment-calibration-logs`,
    CREATE: `${baseUrl}/equipment-calibration-logs`,
    GET: (id) => `${baseUrl}/equipment-calibration-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-calibration-logs/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-calibration-logs/${id}`,
  },
  EQUIPMENT_SAFETY_TEST_LOGS: {
    LIST: `${baseUrl}/equipment-safety-test-logs`,
    CREATE: `${baseUrl}/equipment-safety-test-logs`,
    GET: (id) => `${baseUrl}/equipment-safety-test-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-safety-test-logs/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-safety-test-logs/${id}`,
  },
  EQUIPMENT_DOWNTIME_LOGS: {
    LIST: `${baseUrl}/equipment-downtime-logs`,
    CREATE: `${baseUrl}/equipment-downtime-logs`,
    GET: (id) => `${baseUrl}/equipment-downtime-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-downtime-logs/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-downtime-logs/${id}`,
  },
  EQUIPMENT_SPARE_PARTS: {
    LIST: `${baseUrl}/equipment-spare-parts`,
    CREATE: `${baseUrl}/equipment-spare-parts`,
    GET: (id) => `${baseUrl}/equipment-spare-parts/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-spare-parts/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-spare-parts/${id}`,
  },
  EQUIPMENT_WARRANTY_CONTRACTS: {
    LIST: `${baseUrl}/equipment-warranty-contracts`,
    CREATE: `${baseUrl}/equipment-warranty-contracts`,
    GET: (id) => `${baseUrl}/equipment-warranty-contracts/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-warranty-contracts/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-warranty-contracts/${id}`,
  },
  EQUIPMENT_SERVICE_PROVIDERS: {
    LIST: `${baseUrl}/equipment-service-providers`,
    CREATE: `${baseUrl}/equipment-service-providers`,
    GET: (id) => `${baseUrl}/equipment-service-providers/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-service-providers/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-service-providers/${id}`,
  },
  EQUIPMENT_INCIDENT_REPORTS: {
    LIST: `${baseUrl}/equipment-incident-reports`,
    CREATE: `${baseUrl}/equipment-incident-reports`,
    GET: (id) => `${baseUrl}/equipment-incident-reports/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-incident-reports/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-incident-reports/${id}`,
  },
  EQUIPMENT_RECALL_NOTICES: {
    LIST: `${baseUrl}/equipment-recall-notices`,
    CREATE: `${baseUrl}/equipment-recall-notices`,
    GET: (id) => `${baseUrl}/equipment-recall-notices/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-recall-notices/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-recall-notices/${id}`,
  },
  EQUIPMENT_UTILIZATION_SNAPSHOTS: {
    LIST: `${baseUrl}/equipment-utilization-snapshots`,
    CREATE: `${baseUrl}/equipment-utilization-snapshots`,
    GET: (id) => `${baseUrl}/equipment-utilization-snapshots/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-utilization-snapshots/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-utilization-snapshots/${id}`,
  },
  EQUIPMENT_DISPOSAL_TRANSFERS: {
    LIST: `${baseUrl}/equipment-disposal-transfers`,
    CREATE: `${baseUrl}/equipment-disposal-transfers`,
    GET: (id) => `${baseUrl}/equipment-disposal-transfers/${id}`,
    UPDATE: (id) => `${baseUrl}/equipment-disposal-transfers/${id}`,
    DELETE: (id) => `${baseUrl}/equipment-disposal-transfers/${id}`,
  },
  USERS: {
    LIST: `${baseUrl}/users`,
    CREATE: `${baseUrl}/users`,
    GET: (id) => `${baseUrl}/users/${id}`,
    UPDATE: (id) => `${baseUrl}/users/${id}`,
    DELETE: (id) => `${baseUrl}/users/${id}`,
  },
  PAYMENTS: {
    CREATE: `${baseUrl}/payments`,
    LIST: `${baseUrl}/payments`,
    GET: (id) => `${baseUrl}/payments/${id}`,
    UPDATE: (id) => `${baseUrl}/payments/${id}`,
    DELETE: (id) => `${baseUrl}/payments/${id}`,
    RECONCILE: (id) => `${baseUrl}/payments/${id}/reconcile`,
    CHANNEL_BREAKDOWN: (id) => `${baseUrl}/payments/${id}/channel-breakdown`,
  },
  SUBSCRIPTIONS: {
    LIST: `${baseUrl}/subscriptions`,
    CREATE: `${baseUrl}/subscriptions`,
    GET: (id) => `${baseUrl}/subscriptions/${id}`,
    UPDATE: (id) => `${baseUrl}/subscriptions/${id}`,
    DELETE: (id) => `${baseUrl}/subscriptions/${id}`,
    UPGRADE: (id) => `${baseUrl}/subscriptions/${id}/upgrade`,
    DOWNGRADE: (id) => `${baseUrl}/subscriptions/${id}/downgrade`,
    RENEW: (id) => `${baseUrl}/subscriptions/${id}/renew`,
    PRORATION_PREVIEW: (id) => `${baseUrl}/subscriptions/${id}/proration-preview`,
    USAGE_SUMMARY: (id) => `${baseUrl}/subscriptions/${id}/usage-summary`,
    FIT_CHECK: (id) => `${baseUrl}/subscriptions/${id}/fit-check`,
    UPGRADE_RECOMMENDATION: (id) =>
      `${baseUrl}/subscriptions/${id}/upgrade-recommendation`,
  },
  SUBSCRIPTION_PLANS: {
    LIST: `${baseUrl}/subscription-plans`,
    CREATE: `${baseUrl}/subscription-plans`,
    GET: (id) => `${baseUrl}/subscription-plans/${id}`,
    UPDATE: (id) => `${baseUrl}/subscription-plans/${id}`,
    DELETE: (id) => `${baseUrl}/subscription-plans/${id}`,
    ENTITLEMENTS: (id) => `${baseUrl}/subscription-plans/${id}/entitlements`,
    ADD_ON_ELIGIBILITY: (id) =>
      `${baseUrl}/subscription-plans/${id}/add-on-eligibility`,
  },
  SUBSCRIPTION_INVOICES: {
    LIST: `${baseUrl}/subscription-invoices`,
    CREATE: `${baseUrl}/subscription-invoices`,
    GET: (id) => `${baseUrl}/subscription-invoices/${id}`,
    UPDATE: (id) => `${baseUrl}/subscription-invoices/${id}`,
    DELETE: (id) => `${baseUrl}/subscription-invoices/${id}`,
    COLLECT: (id) => `${baseUrl}/subscription-invoices/${id}/collect`,
    RETRY: (id) => `${baseUrl}/subscription-invoices/${id}/retry`,
  },
  MODULES: {
    LIST: `${baseUrl}/modules`,
    CREATE: `${baseUrl}/modules`,
    GET: (id) => `${baseUrl}/modules/${id}`,
    UPDATE: (id) => `${baseUrl}/modules/${id}`,
    DELETE: (id) => `${baseUrl}/modules/${id}`,
  },
  MODULE_SUBSCRIPTIONS: {
    LIST: `${baseUrl}/module-subscriptions`,
    CREATE: `${baseUrl}/module-subscriptions`,
    GET: (id) => `${baseUrl}/module-subscriptions/${id}`,
    UPDATE: (id) => `${baseUrl}/module-subscriptions/${id}`,
    DELETE: (id) => `${baseUrl}/module-subscriptions/${id}`,
    ACTIVATE: (id) => `${baseUrl}/module-subscriptions/${id}/activate`,
    DEACTIVATE: (id) => `${baseUrl}/module-subscriptions/${id}/deactivate`,
    ELIGIBILITY_CHECK: (id) =>
      `${baseUrl}/module-subscriptions/${id}/eligibility-check`,
  },
  LICENSES: {
    LIST: `${baseUrl}/licenses`,
    CREATE: `${baseUrl}/licenses`,
    GET: (id) => `${baseUrl}/licenses/${id}`,
    UPDATE: (id) => `${baseUrl}/licenses/${id}`,
    DELETE: (id) => `${baseUrl}/licenses/${id}`,
  },
  AUDIT_LOGS: {
    LIST: `${baseUrl}/audit-logs`,
    GET: (id) => `${baseUrl}/audit-logs/${id}`,
  },
  PHI_ACCESS_LOGS: {
    LIST: `${baseUrl}/phi-access-logs`,
    CREATE: `${baseUrl}/phi-access-logs`,
    GET: (id) => `${baseUrl}/phi-access-logs/${id}`,
    GET_BY_USER: (userId) => `${baseUrl}/phi-access-logs/user/${userId}`,
  },
  DATA_PROCESSING_LOGS: {
    LIST: `${baseUrl}/data-processing-logs`,
    CREATE: `${baseUrl}/data-processing-logs`,
    GET: (id) => `${baseUrl}/data-processing-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/data-processing-logs/${id}`,
    DELETE: (id) => `${baseUrl}/data-processing-logs/${id}`,
  },
  BREACH_NOTIFICATIONS: {
    LIST: `${baseUrl}/breach-notifications`,
    CREATE: `${baseUrl}/breach-notifications`,
    GET: (id) => `${baseUrl}/breach-notifications/${id}`,
    UPDATE: (id) => `${baseUrl}/breach-notifications/${id}`,
    RESOLVE: (id) => `${baseUrl}/breach-notifications/${id}/resolve`,
  },
  SYSTEM_CHANGE_LOGS: {
    LIST: `${baseUrl}/system-change-logs`,
    CREATE: `${baseUrl}/system-change-logs`,
    GET: (id) => `${baseUrl}/system-change-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/system-change-logs/${id}`,
    APPROVE: (id) => `${baseUrl}/system-change-logs/${id}/approve`,
    IMPLEMENT: (id) => `${baseUrl}/system-change-logs/${id}/implement`,
  },
  INTEGRATIONS: {
    LIST: `${baseUrl}/integrations`,
    CREATE: `${baseUrl}/integrations`,
    GET: (id) => `${baseUrl}/integrations/${id}`,
    UPDATE: (id) => `${baseUrl}/integrations/${id}`,
    DELETE: (id) => `${baseUrl}/integrations/${id}`,
    TEST_CONNECTION: (id) => `${baseUrl}/integrations/${id}/test-connection`,
    SYNC_NOW: (id) => `${baseUrl}/integrations/${id}/sync-now`,
  },
  INTEGRATION_LOGS: {
    LIST: `${baseUrl}/integration-logs`,
    GET: (id) => `${baseUrl}/integration-logs/${id}`,
    GET_BY_INTEGRATION: (integrationId) =>
      `${baseUrl}/integration-logs/integration/${integrationId}`,
    REPLAY: (id) => `${baseUrl}/integration-logs/${id}/replay`,
  },
  WEBHOOK_SUBSCRIPTIONS: {
    LIST: `${baseUrl}/webhook-subscriptions`,
    CREATE: `${baseUrl}/webhook-subscriptions`,
    GET: (id) => `${baseUrl}/webhook-subscriptions/${id}`,
    UPDATE: (id) => `${baseUrl}/webhook-subscriptions/${id}`,
    DELETE: (id) => `${baseUrl}/webhook-subscriptions/${id}`,
    REPLAY: (id) => `${baseUrl}/webhook-subscriptions/${id}/replay`,
  },
  ADDRESSES: {
    LIST: `${baseUrl}/addresses`,
    CREATE: `${baseUrl}/addresses`,
    GET: (id) => `${baseUrl}/addresses/${id}`,
    UPDATE: (id) => `${baseUrl}/addresses/${id}`,
    DELETE: (id) => `${baseUrl}/addresses/${id}`,
  },
  CONVERSATIONS: {
    LIST: `${baseUrl}/conversations`,
    CREATE: `${baseUrl}/conversations`,
    GET: (id) => `${baseUrl}/conversations/${id}`,
    UPDATE: (id) => `${baseUrl}/conversations/${id}`,
    DELETE: (id) => `${baseUrl}/conversations/${id}`,
  },
  MESSAGES: {
    LIST: `${baseUrl}/messages`,
    CREATE: `${baseUrl}/messages`,
    GET: (id) => `${baseUrl}/messages/${id}`,
    UPDATE: (id) => `${baseUrl}/messages/${id}`,
    DELETE: (id) => `${baseUrl}/messages/${id}`,
  },
  NOTIFICATIONS: {
    LIST: `${baseUrl}/notifications`,
    CREATE: `${baseUrl}/notifications`,
    GET: (id) => `${baseUrl}/notifications/${id}`,
    UPDATE: (id) => `${baseUrl}/notifications/${id}`,
    DELETE: (id) => `${baseUrl}/notifications/${id}`,
  },
  NOTIFICATION_DELIVERIES: {
    LIST: `${baseUrl}/notification-deliveries`,
    CREATE: `${baseUrl}/notification-deliveries`,
    GET: (id) => `${baseUrl}/notification-deliveries/${id}`,
    UPDATE: (id) => `${baseUrl}/notification-deliveries/${id}`,
    DELETE: (id) => `${baseUrl}/notification-deliveries/${id}`,
  },
  TEMPLATES: {
    LIST: `${baseUrl}/templates`,
    CREATE: `${baseUrl}/templates`,
    GET: (id) => `${baseUrl}/templates/${id}`,
    UPDATE: (id) => `${baseUrl}/templates/${id}`,
    DELETE: (id) => `${baseUrl}/templates/${id}`,
  },
  TEMPLATE_VARIABLES: {
    LIST: `${baseUrl}/template-variables`,
    CREATE: `${baseUrl}/template-variables`,
    GET: (id) => `${baseUrl}/template-variables/${id}`,
    UPDATE: (id) => `${baseUrl}/template-variables/${id}`,
    DELETE: (id) => `${baseUrl}/template-variables/${id}`,
  },
  REPORT_DEFINITIONS: {
    LIST: `${baseUrl}/report-definitions`,
    CREATE: `${baseUrl}/report-definitions`,
    GET: (id) => `${baseUrl}/report-definitions/${id}`,
    UPDATE: (id) => `${baseUrl}/report-definitions/${id}`,
    DELETE: (id) => `${baseUrl}/report-definitions/${id}`,
  },
  REPORT_RUNS: {
    LIST: `${baseUrl}/report-runs`,
    CREATE: `${baseUrl}/report-runs`,
    GET: (id) => `${baseUrl}/report-runs/${id}`,
    UPDATE: (id) => `${baseUrl}/report-runs/${id}`,
    DELETE: (id) => `${baseUrl}/report-runs/${id}`,
  },
  DASHBOARD_WIDGETS: {
    LIST: `${baseUrl}/dashboard-widgets`,
    CREATE: `${baseUrl}/dashboard-widgets`,
    SUMMARY: `${baseUrl}/dashboard-widgets/summary`,
    GET: (id) => `${baseUrl}/dashboard-widgets/${id}`,
    UPDATE: (id) => `${baseUrl}/dashboard-widgets/${id}`,
    DELETE: (id) => `${baseUrl}/dashboard-widgets/${id}`,
  },
  KPI_SNAPSHOTS: {
    LIST: `${baseUrl}/kpi-snapshots`,
    CREATE: `${baseUrl}/kpi-snapshots`,
    GET: (id) => `${baseUrl}/kpi-snapshots/${id}`,
    UPDATE: (id) => `${baseUrl}/kpi-snapshots/${id}`,
    DELETE: (id) => `${baseUrl}/kpi-snapshots/${id}`,
  },
  ANALYTICS_EVENTS: {
    LIST: `${baseUrl}/analytics-events`,
    CREATE: `${baseUrl}/analytics-events`,
    GET: (id) => `${baseUrl}/analytics-events/${id}`,
    UPDATE: (id) => `${baseUrl}/analytics-events/${id}`,
    DELETE: (id) => `${baseUrl}/analytics-events/${id}`,
  },
};
